# Generated by Django 4.0 on 2021-12-26 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
