# Generated by Django 4.0 on 2021-12-27 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_author_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='address',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='author',
            name='profile_pic',
            field=models.ImageField(default='static/images/ava.JPG', upload_to='authors/'),
        ),
    ]
